apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qdbb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/devfile-sample-1/devfile-sample-qdbb@sha256:9d67373155c733cbcb5036fb6109132713b7065357febd81c8af47bfc69b0d61
        name: my-nodejs
        resources: {}
status: {}
