apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-mzkk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-mzkk
    app.kubernetes.io/part-of: devfile-sample-1
  name: dc-metro-map-mzkk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-mzkk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-mzkk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/devfile-sample-1/dc-metro-map-mzkk@sha256:dcf926b8c5711d71a28576a3c40c93eb1ee4fc92f70ef071c35468c37d07c34d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
