apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-xbxa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/devfile-sample-1/dc-metro-map-xbxa@sha256:3b6a0c8ef4c66b4e990868f834fe27440346a0c4e47d509fbb215df2b643cdfb
        name: container-image
        resources: {}
status: {}
