apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testsample-go-pwhl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testsample-go-pwhl
    app.kubernetes.io/part-of: devfile-sample-1
  name: testsample-go-pwhl
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: testsample-go-pwhl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: testsample-go-pwhl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/devfile-sample-1/testsample-go-pwhl@sha256:f43e43642db1fb215c0a84c24e454989b190a21d6dfc6c019a2a489e54083128
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
